### ISSUE TITLE
Frontend not working on Firefox or Edge

### ISSUE THREAD

**Issue by brvheem** [DependencyTrack/frontend#34] opened 2020-08-10 08:29 UTC
The new frontend in the latest version of dependency track is only working on Google Chrome.

**Comment by tdillan** [comment] 2020-08-25 15:45
I can confirm this isn't working in the ESR version of Firefox I'm using (major version 68), since it lacks support for `Promise.prototype.finally`.  Would polyfilling that feature resolve the issue?

**Comment by stevespringett** [comment] 2020-09-02 02:00
I've confirmed this to be an issue with Edge (legacy), although new Edge should work fine. 

I've also confirmed the fix works on Edge (legacy). I have not confirmed or tested with ESR FireFox, but I would assume it should work as well. If so, then this issue should be resolved in the next release of Dependency-Track, v4.0.

**Closed** 2021-02-10 05:02 UTC
Labels: defect, pending release
