### ISSUE TITLE
Dependency Graph: Cutoff level, expand-all and package-hyperlinking

### ISSUE THREAD

**Issue by lsauer** [DependencyTrack/frontend#212] opened 2022-07-27 13:48 UTC
Currently in DT 4.5, the dependency graph is quite limited. It does not work for all projects and CycloneDX versions. Sometimes it is just the root and nothing else, despite the import data structure having many package references

### Current Behavior:
- the tree has a cutoff at 3rd depth level
- double click on a node only expands
- the package name is not hyperlinked

### Proposed Behavior:
- don't cutoff at any level
- double click on a node expands all subnodes
- the package name is hyperlinked and references the package entry page

Is someone working on this, or can I implement it and make a Pull request?

**Comment by nscuro** [comment] 2022-07-28 12:07
As @msymons pointed out, this is largely a duplicate of #85. 

@lsauer, please add your additional asks to that issue so that we have everything in a central place. Thanks!

**Closed by nscuro** 2022-07-28 12:07 UTC
Labels: duplicate, enhancement
