### ISSUE TITLE
Inconsistent URL encoding of External Reference URLs

### ISSUE THREAD

**Issue by Robert-Studdock** [DependencyTrack/frontend#933] opened 2024-07-04 04:06 UTC
### Current Behavior

Uploading a BOM containing external references with BOM validation enabled enforces that URLs cannot contain unsafe URL ASCII characters such as spaces. Uploading a URL encoded external reference results in inconsistent results from the UI.

Using the direct link to external references on a project page works with URL encoded external references. However, following an external link from 'Project > View Details > External References' re-encodes the already encoded string: 
`<a href="http://localhost:5000/foo%2520bar">http://localhost:5000/foo%20bar</a>`
While the menu item does not:
`<a role="menuitem" href="http://localhost:5000/foo%20bar" rel="noopener" target="_blank" class="dropdown-item">`

### Steps to Reproduce

1. Enable BOM Validation
2. Upload BOM containing external references e.g.
```
"externalReferences": [
  {
    "url": "http://localhost:5000/foo%20bar",
    "type": "vcs"
  }
```
3. Navigate to project and use external references button to navigate successfully to URL
4. Navigate to project > 'View project details' > 'External References' and click on URL to see 404

### Expected Behavior

External reference URLs in project details screen should work the same as the external references links on project page. 

### Dependency-Track Frontend Version

4.11.4

### Browser

Microsoft Edge

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by msymons** [comment] 2024-07-04 16:24
This is a duplicate of #800

**Closed by msymons** 2024-07-04 16:24 UTC
Labels: duplicate
